### ISSUE TITLE
Docker Image - Host Not Found, Connection Times Out

### ISSUE THREAD

**Issue by merlinstardust** [martinhbramwell/Meteor-CI-Tutorial#40]
I've started your tutorial with the Docker image and I'm already stuck. When I run `ssh-keygen`, I'm told the IP is not found in the `known_hosts` file.

```
$ ssh-keygen -f "~/.ssh/known_hosts" -R ${ip_ct_test};
Host 172.17.0.2 not found in /c/Users/merlin/.ssh/known_hosts
```

I assume this is actually okay because the comment above is about preventing collisions. But then I proceed and attempt to `ssh` in and I get a time out error

```
$ ssh ${ip_ct_test}
ssh: connect to host 172.17.0.2 port 22: Connection timed out
```

Thoughts on the issue?

**Comment by martinhbramwell** [comment]
Yes you can ignore that `ssh-keygen` error message.
For the other, please try ...

```
docker ps -a
```

... and ...

```
docker ps
```

The first lists all your created containers.  The second lists all created containers that are actually running.
I suspect you just need to do 

```
docker start ${  your container   }
```

**Comment by merlinstardust** [comment]
`docker ps` lists my container as running. I ran the `docker start` command anyway and tried `ssh` again. I got the same timeout error.

I am trying to do this on Windows though I don't think that should make much of a difference

**Comment by merlinstardust** [comment]
Figured it out. Apparently I need to `ssh` into the Docker machine first and then `ssh` into the container.

```
$ docker-machine ssh default
docker@default:~$ ssh yourself@172.17.0.2
```

Alternatively to save a line of type

```
 docker exec -u yourself -it ${CONTAINER} /bin/bash
```

**Comment by martinhbramwell** [comment]
Oh dear.  That's a Windows  "thing"  I knew nothing about.

In that case, you are running a virtual machine in a virtual machine. :-(

If you have some alternative virtualization, (eg, VMWare, VirtualBox, Hyper-V) etc. that you prefer and that runs Xubuntu correctly, you might be better off.  I don't know.  I really don't know much about Windows.
